src/Entity/Book.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookRepository")
 */
class Book
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Title;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $PurchasedDate;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Author", inversedBy="books", cascade={"persist"})
     */
    private $author;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Owner", inversedBy="books", cascade={"persist"})
     */
    private $Owner;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\CollectionName", inversedBy="books", cascade={"persist"})
     */
    private $CollectionName;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $NumberOfPages;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $Shelf;

    /**
     * @return mixed
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * @param mixed $author
     * @return Book
     */
    public function setAuthor($author)
    {
        $this->author = $author;
        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getPurchasedDate(): ?\DateTimeInterface
    {
        return $this->PurchasedDate;
    }

    public function setPurchasedDate(?\DateTimeInterface $PurchasedDate): self
    {
        $this->PurchasedDate = $PurchasedDate;

        return $this;
    }

    public function getOwner(): ?Owner
    {
        return $this->Owner;
    }

    public function setOwner(?Owner $Owner): self
    {
        $this->Owner = $Owner;

        return $this;
    }

    public function getCollectionName(): ?CollectionName
    {
        return $this->CollectionName;
    }

    public function setCollectionName(?CollectionName $CollectionName): self
    {
        $this->CollectionName = $CollectionName;

        return $this;
    }
    public function getNumberOfPages(): ?int
    {
        return $this->NumberOfPages;
    }

    public function setNumberOfPages(?int $NumberOfPages): self
    {
        $this->NumberOfPages = $NumberOfPages;

        return $this;
    }

    public function getShelf(): ?int
    {
        return $this->Shelf;
    }

    public function setShelf(?int $Shelf): self
    {
        $this->Shelf = $Shelf;

        return $this;
    }
}

src/Entity/Owner.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OwnerRepository")
 */
class Owner
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Firstname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Lastname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Nickname;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Book", mappedBy="Owner")
     */
    private $books;

    public function __construct()
    {
        $this->books = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->Firstname;
    }

    public function setFirstname(?string $Firstname): self
    {
        $this->Firstname = $Firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->Lastname;
    }

    public function setLastname(?string $Lastname): self
    {
        $this->Lastname = $Lastname;

        return $this;
    }

    public function getNickname(): ?string
    {
        return $this->Nickname;
    }

    public function setNickname(?string $Nickname): self
    {
        $this->Nickname = $Nickname;

        return $this;
    }

    /**
     * @return Collection|Book[]
     */
    public function getBooks(): Collection
    {
        return $this->books;
    }

    public function addBook(Book $book): self
    {
        if (!$this->books->contains($book)) {
            $this->books[] = $book;
            $book->setOwner($this);
        }

        return $this;
    }

    public function removeBook(Book $book): self
    {
        if ($this->books->contains($book)) {
            $this->books->removeElement($book);
            // set the owning side to null (unless already changed)
            if ($book->getOwner() === $this) {
                $book->setOwner(null);
            }
        }

        return $this;
    }
}

src/Form/BookType.php
<?php

namespace App\Form;

use App\Entity\Author;
use App\Entity\Book;
use App\Entity\CollectionName;
use App\Entity\Owner;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Title', TextType::class)
            ->add('Author', EntityType::class, [
                'class' => Author::class,
                'choice_label' => 'Lastname',
                'multiple' => false
            ])
            ->add('Owner', EntityType::class, [
                'class' => Owner::class,
                'choice_label' => 'Firstname',
                'multiple' => false
            ])
            ->add('PurchasedDate', DateType::class)
            ->add('CollectionName', EntityType::class, [
                'class' => CollectionName::class,
                'choice_label' => 'Name',
                'multiple' => false
            ])
            ->add('NumberOfPages', NumberType::class)
            ->add('Shelf', NumberType::class)
            ->add('Save', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Book::class,
        ]);
    }
}

templates/Book/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BookController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/Users/juliealary/Sites/MyLibrary/src/Controller/BookController.php'|file_link(0) }}">src/Controller/BookController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/Users/juliealary/Sites/MyLibrary/templates/book/index.html.twig'|file_link(0) }}">templates/book/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/Book/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="jumbotron">
        <h1 class="text-center">List of Books</h1>
    </div>

    <div class="bookList">
        <table id="myTable" class="display" style="width: 100%">
            <thead>
            <th>id</th>
            <th>title</th>
            <th>owner</th>
            <th>Author</th>
            </thead>
            {% for books in bookList %}
            <tbody>
                <tr>
                    <td>{{ books.id }}</td>
                    <td>{{ books.title }}</td>
                    <td>{{ books.owner.firstname }} {{ books.owner.lastname }}</td>
                    <td>{{ books.author.firstname }} {{ books.author.lastname }}</td>
                </tr>
            {% endfor %}
            </tbody>
            <tfoot>
            <th>ID</th>
            <th>Title</th>
            <th>Owner</th>
            <th>Author</th>
            </tfoot>
        </table>
    </div>
{% endblock %}

{% block javascripts %} {{ parent() }}s

{% endblock %}

templates/Book/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="jumbotron">
        <h1 class="text-center">Add a new Book</h1>
    </div>
    <div class="form">
        {{ form(form) }}
    </div>
    <div class="my-custom-class-for-errors">
        {{ form_errors(form) }}
    </div>
{% endblock %}